# Generated by Django 5.2.6 on 2025-09-30 17:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0003_alter_service_barber_alter_service_payment_method'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Cliente')),
                ('phone_whatsapp', models.CharField(blank=True, max_length=20, null=True, verbose_name='Fone/WhatsApp')),
            ],
        ),
        migrations.CreateModel(
            name='ServiceType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome do Serviço')),
                ('price', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço')),
                ('estimated_time', models.IntegerField(verbose_name='Tempo Estimado (minutos)')),
            ],
        ),
        migrations.RemoveField(
            model_name='service',
            name='estimated_time',
        ),
        migrations.RemoveField(
            model_name='service',
            name='name',
        ),
        migrations.AddField(
            model_name='service',
            name='client_name',
            field=models.CharField(default='', max_length=100, verbose_name='Nome do Cliente'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='service',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Preço Final'),
        ),
        migrations.AlterField(
            model_name='service',
            name='service_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='services', to='barbershop.servicetype', verbose_name='Tipo de Serviço'),
        ),
    ]
