# Generated by Django 5.2.6 on 2025-09-30 18:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0004_client_servicetype_remove_service_estimated_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='service',
            name='service_type',
        ),
        migrations.AddField(
            model_name='service',
            name='discount',
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=6, verbose_name='Desconto (R$)'),
        ),
        migrations.AddField(
            model_name='service',
            name='service_types',
            field=models.ManyToManyField(related_name='appointments', to='barbershop.servicetype', verbose_name='Tipos de Serviço'),
        ),
    ]
