# Generated by Django 5.2.6 on 2025-10-16 21:52

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('barbershop', '0005_remove_service_service_type_service_discount_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Expense',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=255, verbose_name='Descrição da Despesa')),
                ('value', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor Retirado (R$)')),
                ('expense_date', models.DateField(default=django.utils.timezone.now, verbose_name='Data da Despesa')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'ordering': ['-expense_date'],
            },
        ),
    ]
